services:
  web:
    command: gunicorn day_trader.wsgi -b 0:41000
    container_name: day_trader_web
    environment:
     PYTHONUNBUFFERED: 1
    build:
      context: ./images/django
    ports:
    - '41000'
    volumes:
    - ./day_trader:/day_trader
  cache:
    container_name: day_trader_cache
    image: memcached
    ports:
    - '11211:11211'
  db:
    image: mysql:5.7
    container_name: day_trader_db
    environment:
      MYSQL_DATABASE: day_trader_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
    - '3306:3306'
  lb:
    image: nginx
    command: /service/images/nginx/entrypoint.sh
    container_name: day_trader_lb
    volumes:
      - ./images/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./images:/service/images
    ports:
      - '80:80'
      - '443:443'
  queue:
    image: redis
    container_name: day_trader_queue
    ports:
      - '6379:6379'
  worker:
    container_name: day_trader_worker
    volumes:
    - .:/service/
    build:
      context: ./images/worker

version: '3.6'
