services:
  daytrader_web:
   command: go test .
   environment:
    PYTHONUNBUFFERED: 1
   build:
     context: ../images/web
   volumes:
   - ../src/:/go/src/day_trader
  daytrader_cache:
    image: memcached
  daytrader_db:
    image: mysql
    command: mysqld --max_allowed_packet=256M --max_connections=1024 --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: daytrader
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
    - '3307:3306'

version: '3.6'