services:
  daytrader_web:
   command: go run .
   environment:
    PYTHONUNBUFFERED: 1
   build:
     context: ./images/web
     #dockerfile: Dockerfile-lab
   ports:
   - '41000'
   - '6060'
   volumes:
   - ./src:/go/src/day_trader
  daytrader_cache:
    image: memcached
    ports:
    - '11211:11211'
  daytrader_db:
    image: mysql
    command: mysqld --max_allowed_packet=256M --max_connections=1024 --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: daytrader
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
    - '3306:3306'
  # daytrader_lb:
  #     build:
  #       context: ./images/nginx
  #     command: /service/entrypoint.sh
  #     volumes:
  #       - ./images/nginx/nginx.conf:/etc/nginx/nginx.conf
  #     ports:
  #       - '80:80'
  #       - '443:443'
  daytrader_lb:
    build:
      context: ./images/envoy
    command: /service/entrypoint.sh
    volumes:
      - ./images/envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - '80:80'
      - '443:443'

networks:
  default:
    name: day_trader_default

version: '3.6'