services:
  daytrader_lb:
    build:
      context: ./images/envoy
    command: /service/entrypoint.sh
    volumes:
      - ./images/envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - '80:80'
      - '443:443'

version: '3.6'