services:
  daytrader_web:
   command: go run .
   environment:
    PYTHONUNBUFFERED: 1
   build:
     context: ./images/web
     dockerfile: Dockerfile-lab
   ports:
   - '41000'
   - '6060'
   volumes:
   - ./src:/go/src/day_trader

version: '3.6'