services:
  daytrader_db:
    image: mysql
    command: mysqld --max_allowed_packet=256M --max_connections=1024 --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: daytrader
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
    - '3306:3306'

networks:
  default:
    name: day_trader_default

version: '3.6'