services:
  logging_server:
    build:
      context: ./images/logging
    command:  go run .
    ports: 
      - '40000:40000'
    volumes:
      - ./src:/go/src/logging
  logging_db:
    image: mysql
    command: mysqld --max_allowed_packet=256M --max_connections=1024 --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: logging
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
    - '3308:3306'
  logging_lb:
    build:
      context: ./images/nginx
    command: /service/entrypoint.sh
    volumes:
      - ./images/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '81:80'

networks:
  default:
    name: day_trader_default

version: '3.6'