services:
  # logging_server:
  #   build:
  #     context: ./images/logging
  #     dockerfile: Dockerfile-lab
  #   command:  go run .
  #   environment:
  #     LOGGING_DB_IP: 192.168.1.244 
  #     LOGGING_DB_PORT: 3308
  #     MAX_WORKERS: 10
  #     MAX_QUEUE_LENGTH: 1000
  #   ports: 
  #     - '40000:40000'
  #   volumes:
  #     - ./src:/go/src/logging
  # logging_db:
  #   image: mysql
  #   command: mysqld --max_allowed_packet=256M --max_connections=1024 --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_DATABASE: logging
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  #   ports:
  #   - '3308:3306'
  # logging_lb:
  #   build:
  #     context: ./images/nginx
  #   command: /service/entrypoint.sh
  #   volumes:
  #     - ./images/nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - '81:80'
  logging_lb:
    build:
      context: ./images/envoy
    command: /service/entrypoint.sh
    environment:
      LOGGING_SERVER_IP: 192.168.1.240
      LOGGING_SERVER_PORT: 40000
    volumes:
      - ./images/envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - '81:80'

networks:
  default:
    name: day_trader_default

version: '3.6'