version: '3.6'
services:
  generator:
    command: bash -c "cd /service && go run ./workLoadGenerator.go"
    container_name: workload_generator
    build:
      context: .
      #dockerfile: Dockerfile-lab
    volumes:
    - ./workLoadGenerator.go:/service/workLoadGenerator.go
    - ./workload_files:/service/workload_files
    networks:
      - day_trader_default
  
networks:
  day_trader_default:
    external: true